name = "Wild Westcraft"
author = "west3436"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e158ff22d2bf1022864271b09c6202e22f5db44d47e1b21d9b278018e1fdfe3"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["Fabric", "fabric"]
