name = "Wild Westcraft"
author = "west3436"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce7f37340af73af1f27346746d8094892ce92aacdb2ea902fe560c4057b49a09"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["Fabric", "fabric"]
